name: Test Framework Suite

on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install modules
        run: yarn install
      - name: Run Jest Tests
        run: yarn test:jest

  # TODO: Find out how to run this properly
  # cypress-run:
  #   runs-on: ubuntu-latest
  #   container: cypress/browsers:node16.13.0-chrome95-ff94
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         browser: chrome
