name: Test Framework Suite

on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run Jest Tests
        run: npm run test:jest

  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.13.0-chrome95-ff94
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
